/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

public class App {
  public String getGreeting() {
    int ID = 10;
    String word = "こんにちは SEMonster あなたのIDは" + ID;
    return word;
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
  
}
